#!/usr/bin/env python
# coding: utf-8

# In[58]:


#numpy liabrary
#numpy:= Numeric Python . written in c++ language.
# initialize one d array
import numpy as np
a=np.array((-1,-3,-4,-2))
print(a)
aa=np.array([1,3,4,8,0,36])
print(aa)

print(aa.base.__doc__)


# In[14]:


#initialize 2 d array
b=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b.ndim)
print(b)


# In[18]:


#intialize 3d array
c=np.array([[[3,6,9],[2,5,8],[7,8,9],[1,4,8],[12,11,13]]])
print(c.ndim)
print(c)


# In[6]:


#numpy
import numpy as np
a=np.array([[ 1., 0., 0.],
 [ 0., 1., 2.]])
print(a.ndim)
print(a.shape)


# In[8]:


import numpy as np
arr=np.array([1,2,3,4])
arr
print(np.__version__)#latest numpy version is 1.19.4
type(arr)
arr=np.array(42)#0-D array
arr
arr=np.array([1,2,3,4])#1-D array
arr
arr=np.array([[1,2,3],[4,5,6]])#2-D array
print(arr.ndim)


# In[12]:


import numpy as np
#argmax
#argmin
arr=np.array([1,2,3,4,5,6])
arr.sum()
arr       


# In[16]:


l=[1,2,3]
arr=np.array(l)
type(arr)
arr.mean()


# In[18]:


a=np.array([[1,2,3]])
#shape
#len


# In[2]:


import numpy as np
k=np.array([8,7,5,6,1,89])
j=np.array([0,1,5,4])
k


# In[14]:


k.all.__doc__


# In[23]:


import numpy as np
j=np.array([[2,1,],[5,4]])
j


# In[18]:


print(j.dtype)


# In[25]:


import numpy as np 
dt = np.dtype(np.float64) 
print(dt)


# In[ ]:


typee=np.dtype()


# In[28]:


dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 


# In[42]:


import numpy as np
arr=np.arange(100).reshape(10,10)
arr[0][0]#slicing
#arr1=np.daigonal(())
arr1=np.zeros((3,3))
arr1
#arr2=np.eye()
arr.argmax()
arr.argmin()
arr.max()
arr.min()

#reshape()=it is use to reshape our array in any give demintion.
#arange()=it is ude to print sequence. 
# In[44]:


import numpy as np 

dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 


# In[25]:


import numpy as np
arr=np.random.rand(4,5)


# In[5]:


import numpy as np
#arr=np.random.rand(4,5)
arr=np.array([1,2,3,4,5],dtype="float64")
arr


# In[3]:


import numpy as np
z=np.array([[1,2],[3,4]])
z


# In[5]:


import numpy as np 
dt = np.dtype(np.int32) 
dt


# In[19]:


import numpy as np 

dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype = dt) 
a['age'] 


# In[25]:


#sin=np.sin(array*np.pi/180)
#cos
#tan
#cosec
import numpy as np
arr=np.array([22,23,24,25,26])#degree
z=np.sin(arr*np.pi/180)#raiant in sin
y=np.cos(arr*np.pi/180)
x=np.tan(arr*np.pi/180)

#inverse trignomeric function
print(z)
inverse_sin=np.arcsin(z)
print(inverse_sin)
print(y)
inverse_cos=np.arccos(y)
inverse_cos
inverse_tan=np.



# In[32]:


a=[1,2,3,4,5,8,9] #output=[1,3,6,10]
lst=[]
c=0
for i in a:
    c=i+c
    print(c)
#    print(lst.append(c))
    i=i+1
    lst.append(c)
    


# In[33]:


# input
z="2+3-4*5/10+12*3-4"
print(eval(z))


# In[8]:


#arithmetc operator.
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1)
print(arr2)
addition=arr1+arr2
print(addition)
substraction=arr1-arr2
print(substraction)
divid=arr1/arr2
print(divid)
mod=arr1%arr2
print(mod)
mul=arr1*arr2
print(mul)
np.add
print(np.divide(arr1,arr2))
print(np.mod(arr1,arr2))
print(np.reciprocal(arr1,arr2))


# In[21]:


# string in array
import numpy as np
a1=np.array(["my name is "])
a2=np.array([["suresh"]])

print(np.char.add(a1,a2))
a3=np.array(["we are leaving in jaipur"])
print(np.char.multiply(a3,10))
print(np.char.capitalize(a3))
a4=np.array(["jaipur","delhi","ajmer"])
print(np.char.capitalize(a4))
print(np.char.center(a4,100,fillchar="*"))


# In[24]:


import numpy as np
z=np.array([[[2,5,7,8],[9,10,11,12],[3,14,16,18]]])
z
print(np.max(z))
print(np.min(z))
print(np.median(z))


# In[26]:


import numpy as np
arr=np.arange(100).reshape(10,10)
arr


# In[1]:


import numpy as np
a=np.array([1,2,3])
a.itemsize


# In[29]:


#2d array 
import numpy as np
a=np.array([[1,7,5,9],[6,8,0,7],[23,11,45,96]])
#print(np.sort(a,axis=1))
#for i in a:
#    if i 0:
#        print(i)
#
#print(a.any())
b=np.array([0,1,12,45,0,89,36])
q=np.nonzero(b)
q


# In[35]:


import numpy as np
#np.random.seed(101) #value change nhi hogi constant.
a=np.random.randint(0,100,(10,10))
a


# In[36]:


#view and copy function
import numpy as np
ax1=np.array(["jaipur","kota","raj","loc"])
ax1


# In[38]:


print("id of ax1",id(ax1))
ax2=ax1
print("axis2 value",ax2)


# In[39]:


print("id of axis2",id(ax2))


# In[42]:


ax2=ax1.view()
print("value",ax2)
print("id of ax2 after apply view",id(ax2))
print(id(ax1))


# In[44]:


ax3=ax1.view()
ax4=ax1.copy()
print("value of ax3",ax3)
print(id(ax3))
print(id(ax4))


# In[7]:


#"a"+"A"
a1="a"
a2="A"
z=ord("a")
y=ord("A")
print(z+y)


# In[12]:


#a=9
a=9
print(a%=True)
a


# In[30]:


a="1"
b="100"
z=ord("1")
#y=ord("100")
for i in range(100):
    print(i)
    print(ord(str(i)))
#    i=i+1

#print(z+y)


# In[36]:


exam='1'+'100'
l=[]
for x in exam:
    i1=ord(x)
    l.append(i1)
print(sum(l))


# In[38]:


xa=9
xa%=True#xa=xa%True
print(xa)


# In[ ]:




